#!/bin/bash

t=1

while [ 1 ]
do
	echo 1 > /var/rkm/ledRGB/color
	sleep $t
	echo 10 > /var/rkm/ledRGB/color
	sleep $t
	echo 11 > /var/rkm/ledRGB/color
	sleep $t
	echo 100 > /var/rkm/ledRGB/color
	sleep $t
	echo 101 > /var/rkm/ledRGB/color
	sleep $t
	echo 110 > /var/rkm/ledRGB/color
	sleep $t
	echo 111 > /var/rkm/ledRGB/color
	sleep $t
done
